### ISSUE TITLE
Guzzle Support

### ISSUE THREAD

**Issue by nurikabe** [oneall/php-sdk#1]
Would be awesome if we could use Guzzle in place of oneall_curly.

**Comment by SchlesserClaude** [comment]
What advantages would you get by using Guzzle?

**Comment by nurikabe** [comment]
Personally I would mainly want to use it to attach Guzzle event listeners so that I could log traffic and handle encoding issues at the transport level.

Other advantages that I can see for oneall/php-sdk include:

* Transport mechanism independence
* Synchronous and asynchronous requests
