### ISSUE TITLE
cannot post video on facebook

### ISSUE THREAD

**Issue by alinmiron** [oneall/php-sdk#8]
this is what I get:

  -body: "{"response":{"request":{"date":"Wed, 02 May 2018 16:32:45 +0200","resource":"\/push\/identities\/dc2a20c3-974b-4179-b4f4-13c5abfc4df5\/facebook\/video.json","status":{"flag":"error","code":403,"info":"The video cannot be published. The provider send back an unknown response. Our quality assurance team will immediately have a look at this issue."}}}} 
Can you help? 
Thanks!

**Comment by alinmiron** [comment]
It seems that my problem was due the misconfiguration of the Facebook App. However, the message is not too clear.

**Comment by bhenner** [comment]
Hi, Thanks for this report, we'll try to find out the facebook error message and  make our report more efficient.

Regards,

**Comment by SchlesserClaude** [comment]
Hello,

could you please try again? You should not receive a more meaningful message ;)

Regards,
